// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xmlcall.proto

package com.luxoft.xmlcall.proto;

public final class XmlCall {
  private XmlCall() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(com.luxoft.xmlcall.proto.XmlCall.execType);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code xmlcall.ExecType}
   */
  public enum ExecType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <code>QUERY = 1;</code>
     */
    QUERY(1),
    /**
     * <code>INVOKE = 2;</code>
     */
    INVOKE(2),
    /**
     * <code>EVENT = 3;</code>
     */
    EVENT(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <code>QUERY = 1;</code>
     */
    public static final int QUERY_VALUE = 1;
    /**
     * <code>INVOKE = 2;</code>
     */
    public static final int INVOKE_VALUE = 2;
    /**
     * <code>EVENT = 3;</code>
     */
    public static final int EVENT_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ExecType valueOf(int value) {
      return forNumber(value);
    }

    public static ExecType forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return QUERY;
        case 2: return INVOKE;
        case 3: return EVENT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ExecType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ExecType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ExecType>() {
            public ExecType findValueByNumber(int number) {
              return ExecType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.luxoft.xmlcall.proto.XmlCall.getDescriptor().getEnumTypes().get(0);
    }

    private static final ExecType[] VALUES = values();

    public static ExecType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ExecType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:xmlcall.ExecType)
  }

  public interface ChaincodeFaultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:xmlcall.ChaincodeFault)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string message = 1;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>optional string message = 1;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code xmlcall.ChaincodeFault}
   */
  public  static final class ChaincodeFault extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:xmlcall.ChaincodeFault)
      ChaincodeFaultOrBuilder {
    // Use ChaincodeFault.newBuilder() to construct.
    private ChaincodeFault(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChaincodeFault() {
      message_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ChaincodeFault(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.luxoft.xmlcall.proto.XmlCall.internal_static_xmlcall_ChaincodeFault_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.luxoft.xmlcall.proto.XmlCall.internal_static_xmlcall_ChaincodeFault_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.luxoft.xmlcall.proto.XmlCall.ChaincodeFault.class, com.luxoft.xmlcall.proto.XmlCall.ChaincodeFault.Builder.class);
    }

    public static final int MESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object message_;
    /**
     * <code>optional string message = 1;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>optional string message = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.luxoft.xmlcall.proto.XmlCall.ChaincodeFault)) {
        return super.equals(obj);
      }
      com.luxoft.xmlcall.proto.XmlCall.ChaincodeFault other = (com.luxoft.xmlcall.proto.XmlCall.ChaincodeFault) obj;

      boolean result = true;
      result = result && getMessage()
          .equals(other.getMessage());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.luxoft.xmlcall.proto.XmlCall.ChaincodeFault parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.luxoft.xmlcall.proto.XmlCall.ChaincodeFault parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.luxoft.xmlcall.proto.XmlCall.ChaincodeFault parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.luxoft.xmlcall.proto.XmlCall.ChaincodeFault parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.luxoft.xmlcall.proto.XmlCall.ChaincodeFault parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.luxoft.xmlcall.proto.XmlCall.ChaincodeFault parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.luxoft.xmlcall.proto.XmlCall.ChaincodeFault parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.luxoft.xmlcall.proto.XmlCall.ChaincodeFault parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.luxoft.xmlcall.proto.XmlCall.ChaincodeFault parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.luxoft.xmlcall.proto.XmlCall.ChaincodeFault parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.luxoft.xmlcall.proto.XmlCall.ChaincodeFault prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code xmlcall.ChaincodeFault}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:xmlcall.ChaincodeFault)
        com.luxoft.xmlcall.proto.XmlCall.ChaincodeFaultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.luxoft.xmlcall.proto.XmlCall.internal_static_xmlcall_ChaincodeFault_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.luxoft.xmlcall.proto.XmlCall.internal_static_xmlcall_ChaincodeFault_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.luxoft.xmlcall.proto.XmlCall.ChaincodeFault.class, com.luxoft.xmlcall.proto.XmlCall.ChaincodeFault.Builder.class);
      }

      // Construct using com.luxoft.xmlcall.proto.XmlCall.ChaincodeFault.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        message_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.luxoft.xmlcall.proto.XmlCall.internal_static_xmlcall_ChaincodeFault_descriptor;
      }

      public com.luxoft.xmlcall.proto.XmlCall.ChaincodeFault getDefaultInstanceForType() {
        return com.luxoft.xmlcall.proto.XmlCall.ChaincodeFault.getDefaultInstance();
      }

      public com.luxoft.xmlcall.proto.XmlCall.ChaincodeFault build() {
        com.luxoft.xmlcall.proto.XmlCall.ChaincodeFault result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.luxoft.xmlcall.proto.XmlCall.ChaincodeFault buildPartial() {
        com.luxoft.xmlcall.proto.XmlCall.ChaincodeFault result = new com.luxoft.xmlcall.proto.XmlCall.ChaincodeFault(this);
        result.message_ = message_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.luxoft.xmlcall.proto.XmlCall.ChaincodeFault) {
          return mergeFrom((com.luxoft.xmlcall.proto.XmlCall.ChaincodeFault)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.luxoft.xmlcall.proto.XmlCall.ChaincodeFault other) {
        if (other == com.luxoft.xmlcall.proto.XmlCall.ChaincodeFault.getDefaultInstance()) return this;
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.luxoft.xmlcall.proto.XmlCall.ChaincodeFault parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.luxoft.xmlcall.proto.XmlCall.ChaincodeFault) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>optional string message = 1;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string message = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string message = 1;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 1;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 1;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:xmlcall.ChaincodeFault)
    }

    // @@protoc_insertion_point(class_scope:xmlcall.ChaincodeFault)
    private static final com.luxoft.xmlcall.proto.XmlCall.ChaincodeFault DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.luxoft.xmlcall.proto.XmlCall.ChaincodeFault();
    }

    public static com.luxoft.xmlcall.proto.XmlCall.ChaincodeFault getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChaincodeFault>
        PARSER = new com.google.protobuf.AbstractParser<ChaincodeFault>() {
      public ChaincodeFault parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ChaincodeFault(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChaincodeFault> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChaincodeFault> getParserForType() {
      return PARSER;
    }

    public com.luxoft.xmlcall.proto.XmlCall.ChaincodeFault getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ChaincodeResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:xmlcall.ChaincodeResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string txid = 1;</code>
     */
    java.lang.String getTxid();
    /**
     * <code>optional string txid = 1;</code>
     */
    com.google.protobuf.ByteString
        getTxidBytes();
  }
  /**
   * Protobuf type {@code xmlcall.ChaincodeResult}
   */
  public  static final class ChaincodeResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:xmlcall.ChaincodeResult)
      ChaincodeResultOrBuilder {
    // Use ChaincodeResult.newBuilder() to construct.
    private ChaincodeResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChaincodeResult() {
      txid_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ChaincodeResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              txid_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.luxoft.xmlcall.proto.XmlCall.internal_static_xmlcall_ChaincodeResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.luxoft.xmlcall.proto.XmlCall.internal_static_xmlcall_ChaincodeResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.luxoft.xmlcall.proto.XmlCall.ChaincodeResult.class, com.luxoft.xmlcall.proto.XmlCall.ChaincodeResult.Builder.class);
    }

    public static final int TXID_FIELD_NUMBER = 1;
    private volatile java.lang.Object txid_;
    /**
     * <code>optional string txid = 1;</code>
     */
    public java.lang.String getTxid() {
      java.lang.Object ref = txid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        txid_ = s;
        return s;
      }
    }
    /**
     * <code>optional string txid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTxidBytes() {
      java.lang.Object ref = txid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        txid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTxidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, txid_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTxidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, txid_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.luxoft.xmlcall.proto.XmlCall.ChaincodeResult)) {
        return super.equals(obj);
      }
      com.luxoft.xmlcall.proto.XmlCall.ChaincodeResult other = (com.luxoft.xmlcall.proto.XmlCall.ChaincodeResult) obj;

      boolean result = true;
      result = result && getTxid()
          .equals(other.getTxid());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TXID_FIELD_NUMBER;
      hash = (53 * hash) + getTxid().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.luxoft.xmlcall.proto.XmlCall.ChaincodeResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.luxoft.xmlcall.proto.XmlCall.ChaincodeResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.luxoft.xmlcall.proto.XmlCall.ChaincodeResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.luxoft.xmlcall.proto.XmlCall.ChaincodeResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.luxoft.xmlcall.proto.XmlCall.ChaincodeResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.luxoft.xmlcall.proto.XmlCall.ChaincodeResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.luxoft.xmlcall.proto.XmlCall.ChaincodeResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.luxoft.xmlcall.proto.XmlCall.ChaincodeResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.luxoft.xmlcall.proto.XmlCall.ChaincodeResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.luxoft.xmlcall.proto.XmlCall.ChaincodeResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.luxoft.xmlcall.proto.XmlCall.ChaincodeResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code xmlcall.ChaincodeResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:xmlcall.ChaincodeResult)
        com.luxoft.xmlcall.proto.XmlCall.ChaincodeResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.luxoft.xmlcall.proto.XmlCall.internal_static_xmlcall_ChaincodeResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.luxoft.xmlcall.proto.XmlCall.internal_static_xmlcall_ChaincodeResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.luxoft.xmlcall.proto.XmlCall.ChaincodeResult.class, com.luxoft.xmlcall.proto.XmlCall.ChaincodeResult.Builder.class);
      }

      // Construct using com.luxoft.xmlcall.proto.XmlCall.ChaincodeResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        txid_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.luxoft.xmlcall.proto.XmlCall.internal_static_xmlcall_ChaincodeResult_descriptor;
      }

      public com.luxoft.xmlcall.proto.XmlCall.ChaincodeResult getDefaultInstanceForType() {
        return com.luxoft.xmlcall.proto.XmlCall.ChaincodeResult.getDefaultInstance();
      }

      public com.luxoft.xmlcall.proto.XmlCall.ChaincodeResult build() {
        com.luxoft.xmlcall.proto.XmlCall.ChaincodeResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.luxoft.xmlcall.proto.XmlCall.ChaincodeResult buildPartial() {
        com.luxoft.xmlcall.proto.XmlCall.ChaincodeResult result = new com.luxoft.xmlcall.proto.XmlCall.ChaincodeResult(this);
        result.txid_ = txid_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.luxoft.xmlcall.proto.XmlCall.ChaincodeResult) {
          return mergeFrom((com.luxoft.xmlcall.proto.XmlCall.ChaincodeResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.luxoft.xmlcall.proto.XmlCall.ChaincodeResult other) {
        if (other == com.luxoft.xmlcall.proto.XmlCall.ChaincodeResult.getDefaultInstance()) return this;
        if (!other.getTxid().isEmpty()) {
          txid_ = other.txid_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.luxoft.xmlcall.proto.XmlCall.ChaincodeResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.luxoft.xmlcall.proto.XmlCall.ChaincodeResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object txid_ = "";
      /**
       * <code>optional string txid = 1;</code>
       */
      public java.lang.String getTxid() {
        java.lang.Object ref = txid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          txid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string txid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTxidBytes() {
        java.lang.Object ref = txid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          txid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string txid = 1;</code>
       */
      public Builder setTxid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        txid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string txid = 1;</code>
       */
      public Builder clearTxid() {
        
        txid_ = getDefaultInstance().getTxid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string txid = 1;</code>
       */
      public Builder setTxidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        txid_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:xmlcall.ChaincodeResult)
    }

    // @@protoc_insertion_point(class_scope:xmlcall.ChaincodeResult)
    private static final com.luxoft.xmlcall.proto.XmlCall.ChaincodeResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.luxoft.xmlcall.proto.XmlCall.ChaincodeResult();
    }

    public static com.luxoft.xmlcall.proto.XmlCall.ChaincodeResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChaincodeResult>
        PARSER = new com.google.protobuf.AbstractParser<ChaincodeResult>() {
      public ChaincodeResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ChaincodeResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChaincodeResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChaincodeResult> getParserForType() {
      return PARSER;
    }

    public com.luxoft.xmlcall.proto.XmlCall.ChaincodeResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ChaincodeRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:xmlcall.ChaincodeRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string chaincodeId = 1;</code>
     */
    java.lang.String getChaincodeId();
    /**
     * <code>optional string chaincodeId = 1;</code>
     */
    com.google.protobuf.ByteString
        getChaincodeIdBytes();

    /**
     * <code>optional string channel = 2;</code>
     */
    java.lang.String getChannel();
    /**
     * <code>optional string channel = 2;</code>
     */
    com.google.protobuf.ByteString
        getChannelBytes();
  }
  /**
   * Protobuf type {@code xmlcall.ChaincodeRequest}
   */
  public  static final class ChaincodeRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:xmlcall.ChaincodeRequest)
      ChaincodeRequestOrBuilder {
    // Use ChaincodeRequest.newBuilder() to construct.
    private ChaincodeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChaincodeRequest() {
      chaincodeId_ = "";
      channel_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ChaincodeRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              chaincodeId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              channel_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.luxoft.xmlcall.proto.XmlCall.internal_static_xmlcall_ChaincodeRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.luxoft.xmlcall.proto.XmlCall.internal_static_xmlcall_ChaincodeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.luxoft.xmlcall.proto.XmlCall.ChaincodeRequest.class, com.luxoft.xmlcall.proto.XmlCall.ChaincodeRequest.Builder.class);
    }

    public static final int CHAINCODEID_FIELD_NUMBER = 1;
    private volatile java.lang.Object chaincodeId_;
    /**
     * <code>optional string chaincodeId = 1;</code>
     */
    public java.lang.String getChaincodeId() {
      java.lang.Object ref = chaincodeId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        chaincodeId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string chaincodeId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getChaincodeIdBytes() {
      java.lang.Object ref = chaincodeId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chaincodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHANNEL_FIELD_NUMBER = 2;
    private volatile java.lang.Object channel_;
    /**
     * <code>optional string channel = 2;</code>
     */
    public java.lang.String getChannel() {
      java.lang.Object ref = channel_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        channel_ = s;
        return s;
      }
    }
    /**
     * <code>optional string channel = 2;</code>
     */
    public com.google.protobuf.ByteString
        getChannelBytes() {
      java.lang.Object ref = channel_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        channel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getChaincodeIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, chaincodeId_);
      }
      if (!getChannelBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, channel_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getChaincodeIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, chaincodeId_);
      }
      if (!getChannelBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, channel_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.luxoft.xmlcall.proto.XmlCall.ChaincodeRequest)) {
        return super.equals(obj);
      }
      com.luxoft.xmlcall.proto.XmlCall.ChaincodeRequest other = (com.luxoft.xmlcall.proto.XmlCall.ChaincodeRequest) obj;

      boolean result = true;
      result = result && getChaincodeId()
          .equals(other.getChaincodeId());
      result = result && getChannel()
          .equals(other.getChannel());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + CHAINCODEID_FIELD_NUMBER;
      hash = (53 * hash) + getChaincodeId().hashCode();
      hash = (37 * hash) + CHANNEL_FIELD_NUMBER;
      hash = (53 * hash) + getChannel().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.luxoft.xmlcall.proto.XmlCall.ChaincodeRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.luxoft.xmlcall.proto.XmlCall.ChaincodeRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.luxoft.xmlcall.proto.XmlCall.ChaincodeRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.luxoft.xmlcall.proto.XmlCall.ChaincodeRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.luxoft.xmlcall.proto.XmlCall.ChaincodeRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.luxoft.xmlcall.proto.XmlCall.ChaincodeRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.luxoft.xmlcall.proto.XmlCall.ChaincodeRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.luxoft.xmlcall.proto.XmlCall.ChaincodeRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.luxoft.xmlcall.proto.XmlCall.ChaincodeRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.luxoft.xmlcall.proto.XmlCall.ChaincodeRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.luxoft.xmlcall.proto.XmlCall.ChaincodeRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code xmlcall.ChaincodeRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:xmlcall.ChaincodeRequest)
        com.luxoft.xmlcall.proto.XmlCall.ChaincodeRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.luxoft.xmlcall.proto.XmlCall.internal_static_xmlcall_ChaincodeRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.luxoft.xmlcall.proto.XmlCall.internal_static_xmlcall_ChaincodeRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.luxoft.xmlcall.proto.XmlCall.ChaincodeRequest.class, com.luxoft.xmlcall.proto.XmlCall.ChaincodeRequest.Builder.class);
      }

      // Construct using com.luxoft.xmlcall.proto.XmlCall.ChaincodeRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        chaincodeId_ = "";

        channel_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.luxoft.xmlcall.proto.XmlCall.internal_static_xmlcall_ChaincodeRequest_descriptor;
      }

      public com.luxoft.xmlcall.proto.XmlCall.ChaincodeRequest getDefaultInstanceForType() {
        return com.luxoft.xmlcall.proto.XmlCall.ChaincodeRequest.getDefaultInstance();
      }

      public com.luxoft.xmlcall.proto.XmlCall.ChaincodeRequest build() {
        com.luxoft.xmlcall.proto.XmlCall.ChaincodeRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.luxoft.xmlcall.proto.XmlCall.ChaincodeRequest buildPartial() {
        com.luxoft.xmlcall.proto.XmlCall.ChaincodeRequest result = new com.luxoft.xmlcall.proto.XmlCall.ChaincodeRequest(this);
        result.chaincodeId_ = chaincodeId_;
        result.channel_ = channel_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.luxoft.xmlcall.proto.XmlCall.ChaincodeRequest) {
          return mergeFrom((com.luxoft.xmlcall.proto.XmlCall.ChaincodeRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.luxoft.xmlcall.proto.XmlCall.ChaincodeRequest other) {
        if (other == com.luxoft.xmlcall.proto.XmlCall.ChaincodeRequest.getDefaultInstance()) return this;
        if (!other.getChaincodeId().isEmpty()) {
          chaincodeId_ = other.chaincodeId_;
          onChanged();
        }
        if (!other.getChannel().isEmpty()) {
          channel_ = other.channel_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.luxoft.xmlcall.proto.XmlCall.ChaincodeRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.luxoft.xmlcall.proto.XmlCall.ChaincodeRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object chaincodeId_ = "";
      /**
       * <code>optional string chaincodeId = 1;</code>
       */
      public java.lang.String getChaincodeId() {
        java.lang.Object ref = chaincodeId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          chaincodeId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string chaincodeId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getChaincodeIdBytes() {
        java.lang.Object ref = chaincodeId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          chaincodeId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string chaincodeId = 1;</code>
       */
      public Builder setChaincodeId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        chaincodeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string chaincodeId = 1;</code>
       */
      public Builder clearChaincodeId() {
        
        chaincodeId_ = getDefaultInstance().getChaincodeId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string chaincodeId = 1;</code>
       */
      public Builder setChaincodeIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        chaincodeId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object channel_ = "";
      /**
       * <code>optional string channel = 2;</code>
       */
      public java.lang.String getChannel() {
        java.lang.Object ref = channel_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          channel_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string channel = 2;</code>
       */
      public com.google.protobuf.ByteString
          getChannelBytes() {
        java.lang.Object ref = channel_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          channel_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string channel = 2;</code>
       */
      public Builder setChannel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        channel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string channel = 2;</code>
       */
      public Builder clearChannel() {
        
        channel_ = getDefaultInstance().getChannel();
        onChanged();
        return this;
      }
      /**
       * <code>optional string channel = 2;</code>
       */
      public Builder setChannelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        channel_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:xmlcall.ChaincodeRequest)
    }

    // @@protoc_insertion_point(class_scope:xmlcall.ChaincodeRequest)
    private static final com.luxoft.xmlcall.proto.XmlCall.ChaincodeRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.luxoft.xmlcall.proto.XmlCall.ChaincodeRequest();
    }

    public static com.luxoft.xmlcall.proto.XmlCall.ChaincodeRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChaincodeRequest>
        PARSER = new com.google.protobuf.AbstractParser<ChaincodeRequest>() {
      public ChaincodeRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ChaincodeRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChaincodeRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChaincodeRequest> getParserForType() {
      return PARSER;
    }

    public com.luxoft.xmlcall.proto.XmlCall.ChaincodeRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int EXEC_TYPE_FIELD_NUMBER = 51234;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      com.luxoft.xmlcall.proto.XmlCall.ExecType> execType = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.luxoft.xmlcall.proto.XmlCall.ExecType.class,
        null);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xmlcall_ChaincodeFault_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xmlcall_ChaincodeFault_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xmlcall_ChaincodeResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xmlcall_ChaincodeResult_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xmlcall_ChaincodeRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xmlcall_ChaincodeRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rxmlcall.proto\022\007xmlcall\032 google/protobu" +
      "f/descriptor.proto\032\033google/protobuf/empt" +
      "y.proto\"!\n\016ChaincodeFault\022\017\n\007message\030\001 \001" +
      "(\t\"\037\n\017ChaincodeResult\022\014\n\004txid\030\001 \001(\t\"8\n\020C" +
      "haincodeRequest\022\023\n\013chaincodeId\030\001 \001(\t\022\017\n\007" +
      "channel\030\002 \001(\t*9\n\010ExecType\022\013\n\007UNKNOWN\020\000\022\t" +
      "\n\005QUERY\020\001\022\n\n\006INVOKE\020\002\022\t\n\005EVENT\020\003:F\n\texec" +
      "_type\022\036.google.protobuf.MethodOptions\030\242\220" +
      "\003 \001(\0162\021.xmlcall.ExecTypeB#\n\030com.luxoft.x" +
      "mlcall.protoB\007XmlCallb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_xmlcall_ChaincodeFault_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_xmlcall_ChaincodeFault_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xmlcall_ChaincodeFault_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_xmlcall_ChaincodeResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_xmlcall_ChaincodeResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xmlcall_ChaincodeResult_descriptor,
        new java.lang.String[] { "Txid", });
    internal_static_xmlcall_ChaincodeRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_xmlcall_ChaincodeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xmlcall_ChaincodeRequest_descriptor,
        new java.lang.String[] { "ChaincodeId", "Channel", });
    execType.internalInit(descriptor.getExtensions().get(0));
    com.google.protobuf.DescriptorProtos.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
