// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/InsuredRegistry.proto

package com.luxoft.uhg.fabric.services;

public final class InsuredRegistryOuterClass {
  private InsuredRegistryOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf service {@code InsuredRegistry}
   */
  public static abstract class InsuredRegistry
      implements com.google.protobuf.Service {
    protected InsuredRegistry() {}

    public interface Interface {
      /**
       * <code>rpc AddMembers(.main.MemberList) returns (.google.protobuf.Empty);</code>
       */
      public abstract void addMembers(
          com.google.protobuf.RpcController controller,
          com.luxoft.uhg.fabric.proto.InsuredRegistry.MemberList request,
          com.google.protobuf.RpcCallback<com.google.protobuf.Empty> done);

      /**
       * <code>rpc GetChannel(.main.GetChannel) returns (.main.ChannelId);</code>
       */
      public abstract void getChannel(
          com.google.protobuf.RpcController controller,
          com.luxoft.uhg.fabric.proto.InsuredRegistry.GetChannel request,
          com.google.protobuf.RpcCallback<com.luxoft.uhg.fabric.proto.InsuredRegistry.ChannelId> done);

      /**
       * <code>rpc GetAllMembers(.google.protobuf.Empty) returns (.main.MemberList);</code>
       */
      public abstract void getAllMembers(
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Empty request,
          com.google.protobuf.RpcCallback<com.luxoft.uhg.fabric.proto.InsuredRegistry.MemberList> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new InsuredRegistry() {
        @java.lang.Override
        public  void addMembers(
            com.google.protobuf.RpcController controller,
            com.luxoft.uhg.fabric.proto.InsuredRegistry.MemberList request,
            com.google.protobuf.RpcCallback<com.google.protobuf.Empty> done) {
          impl.addMembers(controller, request, done);
        }

        @java.lang.Override
        public  void getChannel(
            com.google.protobuf.RpcController controller,
            com.luxoft.uhg.fabric.proto.InsuredRegistry.GetChannel request,
            com.google.protobuf.RpcCallback<com.luxoft.uhg.fabric.proto.InsuredRegistry.ChannelId> done) {
          impl.getChannel(controller, request, done);
        }

        @java.lang.Override
        public  void getAllMembers(
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Empty request,
            com.google.protobuf.RpcCallback<com.luxoft.uhg.fabric.proto.InsuredRegistry.MemberList> done) {
          impl.getAllMembers(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.addMembers(controller, (com.luxoft.uhg.fabric.proto.InsuredRegistry.MemberList)request);
            case 1:
              return impl.getChannel(controller, (com.luxoft.uhg.fabric.proto.InsuredRegistry.GetChannel)request);
            case 2:
              return impl.getAllMembers(controller, (com.google.protobuf.Empty)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.luxoft.uhg.fabric.proto.InsuredRegistry.MemberList.getDefaultInstance();
            case 1:
              return com.luxoft.uhg.fabric.proto.InsuredRegistry.GetChannel.getDefaultInstance();
            case 2:
              return com.google.protobuf.Empty.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.google.protobuf.Empty.getDefaultInstance();
            case 1:
              return com.luxoft.uhg.fabric.proto.InsuredRegistry.ChannelId.getDefaultInstance();
            case 2:
              return com.luxoft.uhg.fabric.proto.InsuredRegistry.MemberList.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc AddMembers(.main.MemberList) returns (.google.protobuf.Empty);</code>
     */
    public abstract void addMembers(
        com.google.protobuf.RpcController controller,
        com.luxoft.uhg.fabric.proto.InsuredRegistry.MemberList request,
        com.google.protobuf.RpcCallback<com.google.protobuf.Empty> done);

    /**
     * <code>rpc GetChannel(.main.GetChannel) returns (.main.ChannelId);</code>
     */
    public abstract void getChannel(
        com.google.protobuf.RpcController controller,
        com.luxoft.uhg.fabric.proto.InsuredRegistry.GetChannel request,
        com.google.protobuf.RpcCallback<com.luxoft.uhg.fabric.proto.InsuredRegistry.ChannelId> done);

    /**
     * <code>rpc GetAllMembers(.google.protobuf.Empty) returns (.main.MemberList);</code>
     */
    public abstract void getAllMembers(
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Empty request,
        com.google.protobuf.RpcCallback<com.luxoft.uhg.fabric.proto.InsuredRegistry.MemberList> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.luxoft.uhg.fabric.services.InsuredRegistryOuterClass.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.addMembers(controller, (com.luxoft.uhg.fabric.proto.InsuredRegistry.MemberList)request,
            com.google.protobuf.RpcUtil.<com.google.protobuf.Empty>specializeCallback(
              done));
          return;
        case 1:
          this.getChannel(controller, (com.luxoft.uhg.fabric.proto.InsuredRegistry.GetChannel)request,
            com.google.protobuf.RpcUtil.<com.luxoft.uhg.fabric.proto.InsuredRegistry.ChannelId>specializeCallback(
              done));
          return;
        case 2:
          this.getAllMembers(controller, (com.google.protobuf.Empty)request,
            com.google.protobuf.RpcUtil.<com.luxoft.uhg.fabric.proto.InsuredRegistry.MemberList>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.luxoft.uhg.fabric.proto.InsuredRegistry.MemberList.getDefaultInstance();
        case 1:
          return com.luxoft.uhg.fabric.proto.InsuredRegistry.GetChannel.getDefaultInstance();
        case 2:
          return com.google.protobuf.Empty.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.google.protobuf.Empty.getDefaultInstance();
        case 1:
          return com.luxoft.uhg.fabric.proto.InsuredRegistry.ChannelId.getDefaultInstance();
        case 2:
          return com.luxoft.uhg.fabric.proto.InsuredRegistry.MemberList.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.luxoft.uhg.fabric.services.InsuredRegistryOuterClass.InsuredRegistry implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void addMembers(
          com.google.protobuf.RpcController controller,
          com.luxoft.uhg.fabric.proto.InsuredRegistry.MemberList request,
          com.google.protobuf.RpcCallback<com.google.protobuf.Empty> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.google.protobuf.Empty.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.google.protobuf.Empty.class,
            com.google.protobuf.Empty.getDefaultInstance()));
      }

      public  void getChannel(
          com.google.protobuf.RpcController controller,
          com.luxoft.uhg.fabric.proto.InsuredRegistry.GetChannel request,
          com.google.protobuf.RpcCallback<com.luxoft.uhg.fabric.proto.InsuredRegistry.ChannelId> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          com.luxoft.uhg.fabric.proto.InsuredRegistry.ChannelId.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.luxoft.uhg.fabric.proto.InsuredRegistry.ChannelId.class,
            com.luxoft.uhg.fabric.proto.InsuredRegistry.ChannelId.getDefaultInstance()));
      }

      public  void getAllMembers(
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Empty request,
          com.google.protobuf.RpcCallback<com.luxoft.uhg.fabric.proto.InsuredRegistry.MemberList> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(2),
          controller,
          request,
          com.luxoft.uhg.fabric.proto.InsuredRegistry.MemberList.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.luxoft.uhg.fabric.proto.InsuredRegistry.MemberList.class,
            com.luxoft.uhg.fabric.proto.InsuredRegistry.MemberList.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.google.protobuf.Empty addMembers(
          com.google.protobuf.RpcController controller,
          com.luxoft.uhg.fabric.proto.InsuredRegistry.MemberList request)
          throws com.google.protobuf.ServiceException;

      public com.luxoft.uhg.fabric.proto.InsuredRegistry.ChannelId getChannel(
          com.google.protobuf.RpcController controller,
          com.luxoft.uhg.fabric.proto.InsuredRegistry.GetChannel request)
          throws com.google.protobuf.ServiceException;

      public com.luxoft.uhg.fabric.proto.InsuredRegistry.MemberList getAllMembers(
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Empty request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.google.protobuf.Empty addMembers(
          com.google.protobuf.RpcController controller,
          com.luxoft.uhg.fabric.proto.InsuredRegistry.MemberList request)
          throws com.google.protobuf.ServiceException {
        return (com.google.protobuf.Empty) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.google.protobuf.Empty.getDefaultInstance());
      }


      public com.luxoft.uhg.fabric.proto.InsuredRegistry.ChannelId getChannel(
          com.google.protobuf.RpcController controller,
          com.luxoft.uhg.fabric.proto.InsuredRegistry.GetChannel request)
          throws com.google.protobuf.ServiceException {
        return (com.luxoft.uhg.fabric.proto.InsuredRegistry.ChannelId) channel.callBlockingMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          com.luxoft.uhg.fabric.proto.InsuredRegistry.ChannelId.getDefaultInstance());
      }


      public com.luxoft.uhg.fabric.proto.InsuredRegistry.MemberList getAllMembers(
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Empty request)
          throws com.google.protobuf.ServiceException {
        return (com.luxoft.uhg.fabric.proto.InsuredRegistry.MemberList) channel.callBlockingMethod(
          getDescriptor().getMethods().get(2),
          controller,
          request,
          com.luxoft.uhg.fabric.proto.InsuredRegistry.MemberList.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:InsuredRegistry)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035service/InsuredRegistry.proto\032\rxmlcall" +
      ".proto\032\033google/protobuf/empty.proto\032\036mes" +
      "sages/InsuredRegistry.proto2\307\001\n\017InsuredR" +
      "egistry\022<\n\nAddMembers\022\020.main.MemberList\032" +
      "\026.google.protobuf.Empty\"\004\220\202\031\002\0225\n\nGetChan" +
      "nel\022\020.main.GetChannel\032\017.main.ChannelId\"\004" +
      "\220\202\031\001\022?\n\rGetAllMembers\022\026.google.protobuf." +
      "Empty\032\020.main.MemberList\"\004\220\202\031\001B#\n\036com.lux" +
      "oft.uhg.fabric.services\210\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.luxoft.xmlcall.proto.XmlCall.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.luxoft.uhg.fabric.proto.InsuredRegistry.getDescriptor(),
        }, assigner);
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.luxoft.xmlcall.proto.XmlCall.execType);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.luxoft.xmlcall.proto.XmlCall.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    com.luxoft.uhg.fabric.proto.InsuredRegistry.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
